# Generated by Django 6.0.3 on 2026-04-06 15:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('remaining_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('part_number', models.CharField(db_index=True, max_length=100, verbose_name='Manufacturer Part Number (MPN)')),
                ('upc_code', models.CharField(blank=True, max_length=12, verbose_name='Barcode/UPC')),
                ('material', models.CharField(blank=True, choices=[('PVC', 'PVC'), ('CPVC', 'CPVC'), ('PEX', 'PEX'), ('COPPER', 'Copper'), ('BRASS', 'Brass'), ('STAINLESS', 'Stainless Steel'), ('ABS', 'ABS')], max_length=50)),
                ('is_lead_free', models.BooleanField(default=False)),
                ('max_pressure_psi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Pressure (PSI)')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Contractor Price')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Public Price')),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage e.g. 15.00', max_digits=5)),
                ('unit_of_measure', models.CharField(choices=[('UNIT', 'Each'), ('FT', 'Feet'), ('RL', 'Roll'), ('BX', 'Box')], default='UNIT', max_length=10)),
                ('quantity_at_hand', models.IntegerField(default=0, verbose_name='Total Physical Stock')),
                ('quantity_allocated', models.IntegerField(default=0, help_text='Sold but not yet shipped/picked up')),
                ('reorder_point', models.PositiveIntegerField(default=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=6, null=True)),
                ('bin_location', models.CharField(blank=True, help_text='Warehouse location (e.g., A-12-B)', max_length=50)),
                ('supplier', models.CharField(blank=True, help_text='Supplier name or info', max_length=255, null=True)),
                ('product_photo', models.FileField(blank=True, null=True, upload_to='inventory/products/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='home.business')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='products', to='home.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('aproved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='home.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='home.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_number', 'brand'], name='home_produc_part_nu_7b8b38_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upc_code'], name='home_produc_upc_cod_8f38e5_idx'),
        ),
    ]
