# Generated by Django 6.0.5 on 2026-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_document_and_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='unit',
            field=models.CharField(default='PCS', max_length=20),
        ),
    ]
