# Generated by Django 6.0.3 on 2026-04-02 21:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='home_produc_name_29ca62_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='home_produc_brand_255b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='home_produc_part_nu_02792d_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_lead_free',
        ),
        migrations.AddField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, help_text='Warehouse location (e.g., A-12-B)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='home.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='connection_size',
            field=models.CharField(default=1, help_text='e.g., 1/2", 3/4", 1-1/4"', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='connection_type',
            field=models.CharField(default=1, help_text='e.g., Sweat, Threaded, Push-Fit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('PVC', 'PVC'), ('CPVC', 'CPVC'), ('PEX', 'PEX'), ('COPPER', 'Copper'), ('BRASS', 'Brass'), ('STAINLESS', 'Stainless Steel'), ('ABS', 'ABS')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='max_pressure_psi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Pressure (PSI)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_allocated',
            field=models.IntegerField(default=0, help_text='Sold but not yet shipped/picked up'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_at_hand',
            field=models.IntegerField(default=0, verbose_name='Total Physical Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Public Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, help_text='URL-friendly name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage e.g. 15.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('UNIT', 'Each'), ('FT', 'Feet'), ('RL', 'Roll'), ('BX', 'Box')], default='UNIT', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Barcode/UPC'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Contractor Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='home.business'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Manufacturer Part Number (MPN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/products/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_number', 'brand'], name='home_produc_part_nu_7b8b38_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upc_code'], name='home_produc_upc_cod_8f38e5_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorys',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_units',
        ),
    ]
