# Generated by Django 6.0.3 on 2026-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.FileField(blank=True, null=True, upload_to='inventory/products/%Y/%m/'),
        ),
    ]
