# Generated by Django 6.0.5 on 2026-05-20 09:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Selling Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
